# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db29998e3e29d50cd02c190a4d324d0c2958e994f54270f21aecc8d4f9763e9ccfb10a170f984e81895c2c365d5e23d03c480b0c3364572eb0369f13a8b0e548

test:
  secret_key_base: a6f4052b01255866ae94cba70f60619a927b4f01991a6608efa333a3e8663f4351a1155c95bbb62daedb048eac19d0668928346f6cedadf0ecff0846c8f24e1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
